language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest

before_deploy:
  - zip -r latest *
  - mkdir -p jobbie-collector-upload
  - mv latest.zip jobbie-collector-upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: &1
      secure: $AWS_SECRET_KEY
    local_dir: jobbie-collector-upload
    skip_cleanup: true
    on: &2
      repo: dfrancoce/jobbie-collector
    bucket: jobbie-collector
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: *1
    bucket: jobbie-collector
    key: latest.zip
    bundle_type: zip
    application: jobbie-collector
    deployment_group: jobbie-collector-deployment-group
    on: *2